from transformers import (
    Gemma3ForConditionalGeneration,
    MllamaForConditionalGeneration, Qwen2VLForConditionalGeneration, Qwen2_5_VLForConditionalGeneration,
)

MODEL_REGISTRY = {
    "gemma-3-4b-it-base": {
        "base_model_path": "/home/pranon/scratch/def-tahmedge/pretrained_models/gemma-3-4b-it",
        "trained_model_path": "",
        "dataset_path": "/home/pranon/projects/def-tahmedge/pranon/llama-factory-training/data/test-cc.json",
        "output_path": "/home/pranon/scratch/def-tahmedge/pranon/experiments/gen-captions/gemma3-base.json",
        "batch_size": 48,
        "generator_class": Gemma3ForConditionalGeneration,
        "trained": False,
    },
    "gemma-3-fewshot": {
        "base_model_path": "/home/pranon/scratch/def-tahmedge/pretrained_models/gemma-3-4b-it",
        "trained_model_path": "",
        "dataset_path": "/home/pranon/projects/def-tahmedge/pranon/llama-factory-training/data/test-cc.json",
        "output_path": "/home/pranon/scratch/def-tahmedge/pranon/experiments/gen-captions/gemma3-fewshot.json",
        "batch_size": 48,
        "generator_class": Gemma3ForConditionalGeneration,
        "trained": False,
    },
    "gemma-3-sft": {
        "base_model_path": "/home/pranon/scratch/def-tahmedge/pretrained_models/gemma-3-4b-it",
        "trained_model_path": "/home/pranon/scratch/def-tahmedge/pranon/experiments/gemma3_SFT-3-epoch-2",
        "dataset_path": "/home/pranon/projects/def-tahmedge/pranon/llama-factory-training/data/test-cc.json",
        "output_path": "/home/pranon/scratch/def-tahmedge/pranon/experiments/gen-captions/gemma3-sft.json",
        "batch_size": 32,
        "generator_class": Gemma3ForConditionalGeneration,
        "trained": True,
    },
    "gemma-3-4b-it-1000-trained": {
        "base_model_path": "/home/pranon/scratch/def-tahmedge/pretrained_models/gemma-3-4b-it",
        "trained_model_path": "/home/pranon/scratch/def-tahmedge/pranon/experiments/gemma3-3-epoch-1000",
        "dataset_path": "/home/pranon/projects/def-tahmedge/pranon/llama-factory-training/data/test-cc.json",
        "output_path": "/home/pranon/scratch/def-tahmedge/pranon/experiments/gen-captions/gemma3-3-epoch-1000-trained.json",
        "batch_size": 48,
        "generator_class": Gemma3ForConditionalGeneration,
        "trained": True,
    },
    "gemma-3-4b-it-10000-trained": {
        "base_model_path": "/home/pranon/scratch/def-tahmedge/pretrained_models/gemma-3-4b-it",
        "trained_model_path": "/home/pranon/scratch/def-tahmedge/pranon/experiments/gemma3-3-epoch-10000",
        "dataset_path": "/home/pranon/projects/def-tahmedge/pranon/llama-factory-training/data/test-cc.json",
        "output_path": "/home/pranon/scratch/def-tahmedge/pranon/experiments/gen-captions/gemma3-3-epoch-10000-trained.json",
        "batch_size": 48,
        "generator_class": Gemma3ForConditionalGeneration,
        "trained": True,
    },
    "gemma-3-4b-it-full-trained": {
        "base_model_path": "/home/pranon/scratch/def-tahmedge/pretrained_models/gemma-3-4b-it",
        "trained_model_path": "/home/pranon/scratch/def-tahmedge/pranon/experiments/gemma3-1-epoch-full-ds",
        "dataset_path": "/home/pranon/projects/def-tahmedge/pranon/llama-factory-training/data/test-cc.json",
        "output_path": "/home/pranon/scratch/def-tahmedge/pranon/experiments/gen-captions/gemma3-3-epoch-full-trained.json",
        "batch_size": 48,
        "generator_class": Gemma3ForConditionalGeneration,
        "trained": True,
    },
    "Llama-32-11B-Vision-base": {
        "base_model_path": "/home/pranon/scratch/def-tahmedge/pretrained_models/Llama-3.2-11B-Vision-Instruct",
        "trained_model_path": "",
        "dataset_path": "/home/pranon/projects/def-tahmedge/pranon/llama-factory-training/data/test-cc.json",
        "output_path": "/home/pranon/scratch/def-tahmedge/pranon/experiments/gen-captions/Llama-3.2-11B-Vision-base.json",
        "batch_size": 16,
        "generator_class": MllamaForConditionalGeneration,
        "trained": False,
    },
    "Llama-32-11B-Vision-fewshot": {
        "base_model_path": "/home/pranon/scratch/def-tahmedge/pretrained_models/Llama-3.2-11B-Vision-Instruct",
        "trained_model_path": "",
        "dataset_path": "/home/pranon/projects/def-tahmedge/pranon/llama-factory-training/data/test-cc.json",
        "output_path": "/home/pranon/scratch/def-tahmedge/pranon/experiments/gen-captions/Llama-3.2-11B-Vision-fewshot.json",
        "batch_size": 16,
        "generator_class": MllamaForConditionalGeneration,
        "trained": False,
    },
    "Llama-32-sft": {
        "base_model_path": "/home/pranon/scratch/def-tahmedge/pretrained_models/Llama-3.2-11B-Vision-Instruct",
        "trained_model_path": "/home/pranon/scratch/def-tahmedge/pranon/experiments/Llama3_SFT-3-epoch-2",
        "dataset_path": "/home/pranon/projects/def-tahmedge/pranon/llama-factory-training/data/test-cc.json",
        "output_path": "/home/pranon/scratch/def-tahmedge/pranon/experiments/gen-captions/Llama-3.2-sft.json",
        "batch_size": 8,
        "generator_class": MllamaForConditionalGeneration,
        "trained": True,
    },
    "Llama-32-11B-Vision-1000-trained": {
        "base_model_path": "/home/pranon/scratch/def-tahmedge/pretrained_models/Llama-3.2-11B-Vision",
        "trained_model_path": "/home/pranon/scratch/def-tahmedge/pranon/experiments/llama32-3-epoch-1000/",
        "dataset_path": "/home/pranon/projects/def-tahmedge/pranon/llama-factory-training/data/test-cc.json",
        "output_path": "/home/pranon/scratch/def-tahmedge/pranon/experiments/gen-captions/Llama-32-11B-Vision-1000-trained.json",
        "batch_size": 16,
        "generator_class": MllamaForConditionalGeneration,
        "trained": True,
    },
    "Llama-32-11B-Vision-10000-trained": {
        "base_model_path": "/home/pranon/scratch/def-tahmedge/pretrained_models/Llama-3.2-11B-Vision",
        "trained_model_path": "/home/pranon/scratch/def-tahmedge/pranon/experiments/llama32-3-epoch-1000/",
        "dataset_path": "/home/pranon/projects/def-tahmedge/pranon/llama-factory-training/data/test-cc.json",
        "output_path": "/home/pranon/scratch/def-tahmedge/pranon/experiments/gen-captions/Llama-32-11B-Vision-10000-trained.json",
        "batch_size": 16,
        "generator_class": MllamaForConditionalGeneration,
        "trained": True,
    },
    "Llama-32-11B-Vision-full-trained": {
        "base_model_path": "/home/pranon/scratch/def-tahmedge/pretrained_models/Llama-3.2-11B-Vision",
        "trained_model_path": "/home/pranon/scratch/def-tahmedge/pranon/experiments/llama32-3-epoch-1000/",
        "dataset_path": "/home/pranon/projects/def-tahmedge/pranon/llama-factory-training/data/test-cc.json",
        "output_path": "/home/pranon/scratch/def-tahmedge/pranon/experiments/gen-captions/Llama-32-11B-Vision-full-trained.json",
        "batch_size": 16,
        "generator_class": MllamaForConditionalGeneration,
        "trained": True,
    },
    "Qwen2-VL-2B-Instruct-base": {
        "base_model_path": "/home/pranon/scratch/def-tahmedge/pretrained_models/Qwen2-VL-2B-Instruct",
        "trained_model_path": "",
        "dataset_path": "/home/pranon/projects/def-tahmedge/pranon/llama-factory-training/data/test-cc.json",
        "output_path": "/home/pranon/scratch/def-tahmedge/pranon/experiments/gen-captions/Qwen2-VL-2B-Instruct-base.json",
        "batch_size": 48,
        "generator_class": Qwen2VLForConditionalGeneration,
        "trained": False,
    },
    "Qwen2-VL-2B-Instruct-fewshot": {
        "base_model_path": "/home/pranon/scratch/def-tahmedge/pretrained_models/Qwen2-VL-2B-Instruct",
        "trained_model_path": "",
        "dataset_path": "/home/pranon/projects/def-tahmedge/pranon/llama-factory-training/data/test-cc.json",
        "output_path": "/home/pranon/scratch/def-tahmedge/pranon/experiments/gen-captions/Qwen2-VL-2B-Instruct-fewshot.json",
        "batch_size": 48,
        "generator_class": Qwen2VLForConditionalGeneration,
        "trained": False,
    },
    "Qwen2-VL-2B-sft": {
        "base_model_path": "/home/pranon/scratch/def-tahmedge/pretrained_models/Qwen2-VL-2B-Instruct",
        "trained_model_path": "/home/pranon/scratch/def-tahmedge/pranon/experiments/Qwen2_2b_SFT-3-epoch-2",
        "dataset_path": "/home/pranon/projects/def-tahmedge/pranon/llama-factory-training/data/test-cc.json",
        "output_path": "/home/pranon/scratch/def-tahmedge/pranon/experiments/gen-captions/Qwen2-VL-2B-sft.json",
        "batch_size": 48,
        "generator_class": Qwen2VLForConditionalGeneration,
        "trained": True,
    },
    "Qwen2-VL-2B-Instruct-1000-trained": {
        "base_model_path": "/home/pranon/scratch/def-tahmedge/pretrained_models/Qwen2-VL-2B-Instruct",
        "trained_model_path": "/home/pranon/scratch/def-tahmedge/pranon/experiments/Qwen2_2bFull-3-epoch-1000",
        "dataset_path": "/home/pranon/projects/def-tahmedge/pranon/llama-factory-training/data/test-cc.json",
        "output_path": "/home/pranon/scratch/def-tahmedge/pranon/experiments/gen-captions/Qwen2-VL-2B-Instruct-1000-trained.json",
        "batch_size": 48,
        "generator_class": Qwen2VLForConditionalGeneration,
        "trained": True,
    },
    "Qwen2-VL-2B-Instruct-10000-trained": {
        "base_model_path": "/home/pranon/scratch/def-tahmedge/pretrained_models/Qwen2-VL-2B-Instruct",
        "trained_model_path": "/home/pranon/scratch/def-tahmedge/pranon/experiments/Qwen2_2bFull-3-epoch-10000",
        "dataset_path": "/home/pranon/projects/def-tahmedge/pranon/llama-factory-training/data/test-cc.json",
        "output_path": "/home/pranon/scratch/def-tahmedge/pranon/experiments/gen-captions/Qwen2-VL-2B-Instruct-10000-trained.json",
        "batch_size": 48,
        "generator_class": Qwen2VLForConditionalGeneration,
        "trained": True,
    },
    "Qwen2-VL-2B-Instruct-full-trained": {
        "base_model_path": "/home/pranon/scratch/def-tahmedge/pretrained_models/Qwen2-VL-2B-Instruct",
        "trained_model_path": "/home/pranon/scratch/def-tahmedge/pranon/experiments/Qwen2_2bFull_1-full-ds",
        "dataset_path": "/home/pranon/projects/def-tahmedge/pranon/llama-factory-training/data/test-cc.json",
        "output_path": "/home/pranon/scratch/def-tahmedge/pranon/experiments/gen-captions/Qwen2-VL-2B-Instruct-full-trained.json",
        "batch_size": 48,
        "generator_class": Qwen2VLForConditionalGeneration,
        "trained": True,
    },
    "Qwen2-VL-7B-Instruct-base": {
        "base_model_path": "/home/pranon/scratch/def-tahmedge/pretrained_models/Qwen2-VL-7B-Instruct",
        "trained_model_path": "",
        "dataset_path": "/home/pranon/projects/def-tahmedge/pranon/llama-factory-training/data/test-cc.json",
        "output_path": "/home/pranon/scratch/def-tahmedge/pranon/experiments/gen-captions/Qwen2-VL-7B-Instruct-base.json",
        "batch_size": 24,
        "generator_class": Qwen2VLForConditionalGeneration,
        "trained": False,
    },
    "Qwen2-VL-7B-Instruct-fewshot": {
        "base_model_path": "/home/pranon/scratch/def-tahmedge/pretrained_models/Qwen2-VL-7B-Instruct",
        "trained_model_path": "",
        "dataset_path": "/home/pranon/projects/def-tahmedge/pranon/llama-factory-training/data/test-cc.json",
        "output_path": "/home/pranon/scratch/def-tahmedge/pranon/experiments/gen-captions/Qwen2-VL-7B-Instruct-fewshot.json",
        "batch_size": 24,
        "generator_class": Qwen2VLForConditionalGeneration,
        "trained": False,
    },
    "Qwen2-VL-7B-sft": {
        "base_model_path": "/home/pranon/scratch/def-tahmedge/pretrained_models/Qwen2-VL-7B-Instruct",
        "trained_model_path": "/home/pranon/scratch/def-tahmedge/pranon/experiments/Qwen2_7b_SFT-3-epoch-2",
        "dataset_path": "/home/pranon/projects/def-tahmedge/pranon/llama-factory-training/data/test-cc.json",
        "output_path": "/home/pranon/scratch/def-tahmedge/pranon/experiments/gen-captions/Qwen2-VL-7B-sft.json",
        "batch_size": 16,
        "generator_class": Qwen2VLForConditionalGeneration,
        "trained": True,
    },
    "Qwen2-VL-7B-Instruct-1000-trained": {
        "base_model_path": "/home/pranon/scratch/def-tahmedge/pretrained_models/Qwen2-VL-7B-Instruct",
        "trained_model_path": "/home/pranon/scratch/def-tahmedge/pranon/experiments/Qwen2_7b-3-epoch-1000",
        "dataset_path": "/home/pranon/projects/def-tahmedge/pranon/llama-factory-training/data/test-cc.json",
        "output_path": "/home/pranon/scratch/def-tahmedge/pranon/experiments/gen-captions/Qwen2-VL-7B-Instruct-1000-trained.json",
        "batch_size": 24,
        "generator_class": Qwen2VLForConditionalGeneration,
        "trained": True,
    },
    "Qwen2-VL-7B-Instruct-10000-trained": {
        "base_model_path": "/home/pranon/scratch/def-tahmedge/pretrained_models/Qwen2-VL-7B-Instruct",
        "trained_model_path": "/home/pranon/scratch/def-tahmedge/pranon/experiments/Qwen2_7b-3-epoch-10000",
        "dataset_path": "/home/pranon/projects/def-tahmedge/pranon/llama-factory-training/data/test-cc.json",
        "output_path": "/home/pranon/scratch/def-tahmedge/pranon/experiments/gen-captions/Qwen2-VL-7B-Instruct-10000-trained.json",
        "batch_size": 24,
        "generator_class": Qwen2VLForConditionalGeneration,
        "trained": True,
    },
    "Qwen2-VL-7B-Instruct-full-trained": {
        "base_model_path": "/home/pranon/scratch/def-tahmedge/pretrained_models/Qwen2-VL-7B-Instruct",
        "trained_model_path": "/home/pranon/scratch/def-tahmedge/pranon/experiments/Qwen2_7bFull-full-ds",
        "dataset_path": "/home/pranon/projects/def-tahmedge/pranon/llama-factory-training/data/test-cc.json",
        "output_path": "/home/pranon/scratch/def-tahmedge/pranon/experiments/gen-captions/Qwen2-VL-7B-Instruct-full-trained.json",
        "batch_size": 24,
        "generator_class": Qwen2VLForConditionalGeneration,
        "trained": True,
    },
    "Qwen25-VL-7B-Instruct-base": {
        "base_model_path": "/home/pranon/scratch/def-tahmedge/pretrained_models/Qwen2.5-VL-7B-Instruct",
        "trained_model_path": "",
        "dataset_path": "/home/pranon/projects/def-tahmedge/pranon/llama-factory-training/data/test-cc.json",
        "output_path": "/home/pranon/scratch/def-tahmedge/pranon/experiments/gen-captions/Qwen25-VL-7B-Instruct-base.json",
        "batch_size": 24,
        "generator_class": Qwen2_5_VLForConditionalGeneration,
        "trained": False,
    },
    "Qwen25-VL-7B-Instruct-fewshot": {
        "base_model_path": "/home/pranon/scratch/def-tahmedge/pretrained_models/Qwen2.5-VL-7B-Instruct",
        "trained_model_path": "",
        "dataset_path": "/home/pranon/projects/def-tahmedge/pranon/llama-factory-training/data/test-cc.json",
        "output_path": "/home/pranon/scratch/def-tahmedge/pranon/experiments/gen-captions/Qwen25-VL-7B-Instruct-fewshot.json",
        "batch_size": 24,
        "generator_class": Qwen2_5_VLForConditionalGeneration,
        "trained": False,
    },
    "Qwen25-VL-7B-sft": {
        "base_model_path": "/home/pranon/scratch/def-tahmedge/pretrained_models/Qwen2.5-VL-7B-Instruct",
        "trained_model_path": "/home/pranon/scratch/def-tahmedge/pranon/experiments/Qwen25_7b_SFT-3-epoch-2",
        "dataset_path": "/home/pranon/projects/def-tahmedge/pranon/llama-factory-training/data/test-cc.json",
        "output_path": "/home/pranon/scratch/def-tahmedge/pranon/experiments/gen-captions/Qwen25-VL-7B-sft.json",
        "batch_size": 16,
        "generator_class": Qwen2_5_VLForConditionalGeneration,
        "trained": True,
    },
    "Qwen25-VL-7B-Instruct-1000-trained": {
        "base_model_path": "/home/pranon/scratch/def-tahmedge/pretrained_models/Qwen2.5-VL-7B-Instruct",
        "trained_model_path": "/home/pranon/scratch/def-tahmedge/pranon/experiments/Qwen25_7b-3-epoch-1000",
        "dataset_path": "/home/pranon/projects/def-tahmedge/pranon/llama-factory-training/data/test-cc.json",
        "output_path": "/home/pranon/scratch/def-tahmedge/pranon/experiments/gen-captions/Qwen25-VL-7B-Instruct-1000-trained.json",
        "batch_size": 24,
        "generator_class": Qwen2_5_VLForConditionalGeneration,
        "trained": True,
    },
    "Qwen25-VL-7B-Instruct-10000-trained": {
        "base_model_path": "/home/pranon/scratch/def-tahmedge/pretrained_models/Qwen2.5-VL-7B-Instruct",
        "trained_model_path": "/home/pranon/scratch/def-tahmedge/pranon/experiments/Qwen25_7b-3-epoch-10000",
        "dataset_path": "/home/pranon/projects/def-tahmedge/pranon/llama-factory-training/data/test-cc.json",
        "output_path": "/home/pranon/scratch/def-tahmedge/pranon/experiments/gen-captions/Qwen25-VL-7B-Instruct-10000-trained.json",
        "batch_size": 24,
        "generator_class": Qwen2_5_VLForConditionalGeneration,
        "trained": True,
    },
    "Qwen25-VL-7B-Instruct-full-trained": {
        "base_model_path": "/home/pranon/scratch/def-tahmedge/pretrained_models/Qwen2.5-VL-7B-Instruct",
        "trained_model_path": "/home/pranon/scratch/def-tahmedge/pranon/experiments/Qwen25_7bFull-full-ds",
        "dataset_path": "/home/pranon/projects/def-tahmedge/pranon/llama-factory-training/data/test-cc.json",
        "output_path": "/home/pranon/scratch/def-tahmedge/pranon/experiments/gen-captions/Qwen25-VL-7B-Instruct-full-trained.json",
        "batch_size": 24,
        "generator_class": Qwen2_5_VLForConditionalGeneration,
        "trained": True,
    },
}
